### ISSUE TITLE
Python segfaults upon artwork loading

### ISSUE THREAD

**Issue by ghzgod** [linuxserver/docker-headphones#17] opened 2017-03-25 02:36 UTC
So I've tried both versions of python within the nerdpack.  No matter what I do, I get

` python[24030]: segfault at 2b15695a9ff8 ip 00002b1560e558ba sp 00002b15695aa000 error 6 in libpython2.7.so.1.0[2b1560df3000+342000]`

This happens often upon settings changes but most often when adding a new artist.  After the segfault error, the headphones docker restarts itself.

**Comment by sparklyballs** [comment] 2017-03-25 09:10
duplicate of #16

**Closed as completed by sparklyballs** 2017-03-25 09:10 UTC
