### ISSUE TITLE
Attempt to query MusicBrainz for queen failed (caused by: )

### ISSUE THREAD

**Issue by ShinobiX9X** [linuxserver/docker-headphones#28] opened 2017-08-23 13:10 UTC
I use openmediavault 3 (is Debian)

Everytime i look for an artist, headphones finds nothing and in the logs that's the only error i find.
If anybody knows what to do, or if i have to check at headphones for what the problem could be?

thanks you

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by Stealthii** [comment] 2017-12-17 14:53
This is a duplicate of #21 (which is the effect you are seeing), which is described in #16. #30 Is tracking the root cause.

**Comment by sparklyballs** [comment] 2017-12-17 14:56
@Stealthii this image is based on python 2.7

**Comment by CHBMB** [comment] 2017-12-17 16:03
Damn, if you're going to link a load of issues together at least make sure you're right, check the source code and commit history for this container, it has never run on Python 3.

**Comment by sparklyballs** [comment] 2018-02-23 05:49
i'm gonna go ahead and close this

**Closed as completed by sparklyballs** 2018-02-23 05:49 UTC
